### ISSUE TITLE
overflow of .twelve.columns div in fixed width tablet portrait view

### ISSUE THREAD

**Issue by dirkolbrich** [atomicpages/skeleton-sass#28]
A `.twelve .column.`wide `<div>` is too wide in iPad portrait screen. It overflows the surrounding `.container`.

Following html setup. Theme is `Fresh`with `$is-fluid: false;`setup:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>sample title</title>
    <link rel="stylesheet" href="/css/main.css">
</head>

<body>
    <!-- .container is main centered wrapper -->
    <div class="container">
        <div class="row">
            <div class="twelve columns">
                <p>This column is too wide for surrounding container in browser width 960 - 1100px</p>
            </div>
        </div>
    </div>
</body>

</html>
```

## Problem

Right in between the sweet spot of 960 - 1100px browser width (iPad is 1024px on portrait), the `.twelve.colums`div is wider than the surrounding `.container` div. I think the reason is `.twelve.colums`has no `max-width`set at that point.

This is caused by the `@media only screen and (min-width: $tablet-width) and (max-width: $base-width - 1) {}` query in `/themes/fresh/_grid.scss:34` as it stops at 959px browser width.

```css
/* TABLET (PORTRAIT) */
@media only screen and (min-width: 768px) and (max-width: 959px) {
  .container {
    width: 768px;
  }
  /* ... */
  .container .twelve.columns {
    width: 748px;
  }
}
```

From there on, the other smaller media queries kick in:

```css
/* For devices larger than 400px */
@media (min-width: 400px) {
  .container {
    width: 85%; /* results to 816px width at 960px browser, needs browser at 1100px width until it is wide enough for .twelve.columns */
  }
}

/* For devices larger than 550px */
@media (min-width: 550px) {
  .container { /* no width set, is by 85% */ }
  .container .twelve.columns {
    width: 940px;
  }
}
```

## Proposed solution

Give all columns a `max-width: 100%` in `/core/_dependencies.scss:96`:

```scss
.#{numToString($i)}.columns { 
  width: $colWidth + (($colWidth + $gutterWidth) * ($i - 1));
  max-width: 100%;
}
```

Yet I don`t know for sure, if this would cause any side effects on other settings.

**Comment by dirkolbrich** [comment]
better solution to set `max-width`for all `.columns` at `/core/_dependencies.scss:83`:

```scss
@mixin _fixedGrid($width, $colWidth, $gutterWidth, $colCount) {
	.container {
		.column,
		.columns {
			max-width: 100%;
			margin: {
				left: $gutterWidth / 2;
				right: $gutterWidth / 2;
			};
		}
	}
	/* The Grid */
       /* ... */
}
```
