### ISSUE TITLE
difference in width of `.one.column` and `.one.columns` in mobile grid

### ISSUE THREAD

**Issue by dirkolbrich** [atomicpages/skeleton-sass#29]
There is a difference in width of `.one.column` and `.one.columns` in mobile grids, but they should be the same.

`.one.column` takes up the full `container` width, but `.one.columns` has margins. Only `.full-width.columns` should take the full width of the `.container`.

Here is the transpiled output css.

```css
/*  MOBILE (PORTRAIT)
 * ------------------------------------------------ */
@media only screen and (max-width: 767px) {
  .container {
    width: 300px;
  }
  .container .column,
  .container .columns {
    margin-left: 0;
    margin-right: 0;
  }
  .container .one.column {
    width: 300px;
  }
  .container .one.columns, .container .two.columns, .container .three.columns, .container .four.columns, .container .five.columns, .container .six.columns, .container .seven.columns, .container .eight.columns, .container .nine.columns, .container .ten.columns, .container .eleven.columns, .container .twelve.columns {
    width: 296px;
  }
  .container .one-third.column {
    width: 296px;
  }
  .container .two-thirds.column {
    width: 296px;
  }
  .container .full-width.columns {
    width: 300px;
    margin-left: 0;
    margin-right: 0;
  }
  .container .offset-by-one, .container .offset-by-two, .container .offset-by-three, .container .offset-by-four, .container .offset-by-five, .container .offset-by-six, .container .offset-by-seven, .container .offset-by-eight, .container .offset-by-nine, .container .offset-by-ten, .container .offset-by-eleven {
    padding-left: 0;
  }
}

/* MOBILE (LANDSCAPE)
 * ------------------------------------------------ */
@media only screen and (min-width: 480px) and (max-width: 767px) {
  .container {
    width: 420px;
  }
  .container .column,
  .container .columns {
    margin-left: 0;
    margin-right: 0;
  }
  .container .one.column {
    width: 420px;
  }
  .container .one.columns, .container .two.columns, .container .three.columns, .container .four.columns, .container .five.columns, .container .six.columns, .container .seven.columns, .container .eight.columns, .container .nine.columns, .container .ten.columns, .container .eleven.columns, .container .twelve.columns {
    width: 416px;
  }
  .container .one-third.column {
    width: 416px;
  }
  .container .two-thirds.column {
    width: 416px;
  }
  .container .full-width.columns {
    width: 420px;
    margin-left: 0;
    margin-right: 0;
  }
  .container .offset-by-one, .container .offset-by-two, .container .offset-by-three, .container .offset-by-four, .container .offset-by-five, .container .offset-by-six, .container .offset-by-seven, .container .offset-by-eight, .container .offset-by-nine, .container .offset-by-ten, .container .offset-by-eleven {
    padding-left: 0;
  }
}
```
