### ISSUE TITLE
overflow of `.colums` over `.container` with fixed grid in small screen size

### ISSUE THREAD

**Issue by dirkolbrich** [atomicpages/skeleton-sass#31]
when set to fixed grid and on small screen size ~320px width, `.column`will overflow `.container` due to standard padding at `.container`in `_grid.scss:8`

```css
/* BASE GRID
 * ------------------------------------------------ */
.container {
	position: relative;
	width: $base-width;
	max-width: $grid-max-width;
	margin: 0 auto;
	padding: 0 relative(20px);
	box-sizing: border-box;
}
```

## Proposed Fix

add `max-width`to columns and delete small subtraction from `width`of `.colums` in `_mobileGrid(){}`

```scss
@mixin _mobileGrid($width, $colCount, $isFluid) {
	$width: if($isFluid, $mobile-fluid-width, $width);
	.container {
		width: $width;
		.column,
		.columns {
			max-width: 100%; // add max-width
			margin: {
				left: if($isFluid, 2%, 0);
				right: if($isFluid, 2%, 0);
			};
		}
		@for $i from 1 through $colCount {
			@if ($i == 1) {
				.#{numToString($i)}.column { width: $width ; }
			}
		}
		@include _group($colCount, ".columns", "after") { width: $width; } // delete -4
		.one-third.column { width: $width; }  // delete -4
		.two-thirds.column { width: $width; }  // delete -4
		.full-width.columns {
			width: $width;
			margin-left: 0;
			margin-right: 0;
		}
		@include _mobileOffset($colCount);
	}
}
```
